### ISSUE TITLE
CMake problem

### ISSUE THREAD

**Issue by Nariman-Eskandari** [cktben/ssl-vision#1]
when I want to Cmake the project
these massage appear :

-- The C compiler identification is GNU 4.7.2
-- The CXX compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found.
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found.
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found.
-- Found Qt4: /usr/bin/qmake (found version "4.8.3") 
-- Build Type: 
-- Arch: x86_64
-- CC Flags: -DNDEBUG -O3 -march=native -Wl,--no-as-needed
-- Custom CC Flags: 
-- Configuring done
-- Generating done

I using ubuntu 12.10 amd64...
I don't know how to solve not found problem ...

**Comment by cktben** [comment]
The "not found" messages are not bugs.  FindQt4 is looking for Qt on all possible platforms. WIN means Windows, QWS is Qt for embedded systems, and MAC is for Macs.  Only one will ever be found, and when building on Linux it will use X11.
